name: Planilha de farm no Discord

on:
  schedule:
    - cron: '1 4 * * 1'  # Toda segunda-feira às 01:01 (BRT / UTC-3)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          # Instalar o ChromeDriver com o webdriver-manager
          curl -sSL https://github.com/ebuchman/installer/releases/download/v1.0.0/install.sh | bash

      - name: Instalar dependências Python
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium requests webdriver-manager

      - name: Rodar script Python
        env:
          PLANILHA_URL: ${{ secrets.PLANILHA_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python3 planilha_discord.py

      - name: Enviar erro para o Discord se o script falhar
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"❌ Falha ao enviar print da planilha de farm! Verifique o GitHub Actions.\"}" \
               ${{ secrets.WEBHOOK_URL }}
