name: Schedule Ping

on:
  schedule:
    - cron: '1 4 * * 1'  # Toda segunda-feira às 01:01 BRT (UTC-3)
  workflow_dispatch:     # Permite execução manual também

jobs:
  send-ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instala dependências (Chrome e unzip)
        run: |
          sudo apt update
          curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt install -y unzip

      - name: Verifica e exibe parte do webhook
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "❌ WEBHOOK_URL não está definido. Abortando envio do ping."
            exit 0
          else
            echo "🔒 WEBHOOK_URL está definido. Início do valor: ${WEBHOOK_URL:0:40}****"
          fi

      - name: Envia ping para o webhook
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{"content":"✅ Ping automático executado com sucesso!"}'

        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
