name: Ping semanal da planilha

on:
  schedule:
    - cron: '1 4 * * 1'  # Toda segunda-feira às 01:01 (BRT / UTC-3)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configura variáveis de ambiente
        run: |
          echo "PLANILHA_URL=${{ secrets.PLANILHA_URL }}" >> $GITHUB_ENV
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Instala dependências (Chrome, unzip, curl)
        run: |
          sudo apt update
          sudo apt install -y unzip curl
          curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt --fix-broken install -y
          google-chrome --version

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instala dependências do Python
        run: |
          pip install selenium webdriver-manager requests

      - name: Executa o script
        run: python planilha_discord.py
