name: Atualizar Planilha no Discord

on:
  schedule:
    - cron: '0 20 * * *'  # 17h BRT (20h UTC)
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Instalar dependências Python
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium requests

      - name: Rodar script Python
        env:
          PLANILHA_URL: ${{ secrets.PLANILHA_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python3 planilha_discord.py
