name: Planilha de farm no Discord

on:
  schedule:
    - cron: '1 4 * * 1'  # Toda segunda-feira às 01:01 (BRT / UTC-3)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y unzip

          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          
          if [ -z "$DRIVER_VERSION" ]; then
            echo "❌ Falha ao obter a versão do ChromeDriver compatível com $CHROME_VERSION"
            exit 1
          fi
          
          curl -sSL "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip" -o /tmp/chromedriver.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Instalar dependências Python
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium requests webdriver-manager

      - name: Rodar script Python
        env:
          PLANILHA_URL: ${{ secrets.PLANILHA_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python3 planilha_discord.py

      - name: Enviar erro para o Discord se o script falhar
        if: failure()
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"❌ Falha ao enviar print da planilha de farm! Verifique o GitHub Actions.\"}" \
               "$WEBHOOK_URL"
