name: Atualizar Planilha no Discord

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

          TARGET="/usr/bin/chromedriver"
          SOURCE="/usr/lib/chromium-browser/chromedriver"

          if [ ! -e "$TARGET" ]; then
            sudo ln -s "$SOURCE" "$TARGET"
          elif [ "$(readlink -f "$TARGET")" != "$SOURCE" ]; then
            sudo rm "$TARGET"
            sudo ln -s "$SOURCE" "$TARGET"
          fi

      - name: Instalar dependências Python
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium requests

      - name: Rodar script Python
        env:
          PLANILHA_URL: ${{ secrets.PLANILHA_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python3 planilha_discord.py

      - name: Enviar erro para o Discord se o script falhar
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"❌ Falha ao enviar print da planilha de farm! Verifique o GitHub Actions.\"}" \
               ${{ secrets.WEBHOOK_URL }}
