name: Atualizar Planilha no Discord

on:
  schedule:
    - cron: '0 20 * * *'  # Hoje às 17h BRT (20h UTC)
  workflow_dispatch:     # Permite rodar manualmente também
  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Instalar dependências do Python
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium requests

      - name: Rodar script com X virtual framebuffer
        env:
          PLANILHA_URL: ${{ secrets.PLANILHA_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          xvfb-run -a python3 planilha_discord.py
